# Generated by Django 3.0.2 on 2020-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200328_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
